version: '2'
services:
  mdm:
    image: erikaulin/micromdm:latest
    volumes:
      - ./certs:/opt/micromdm/certs
      - ./pkgrepo:/opt/micromdm/pkgrepo
    ports:
      - "8443:8443"
    env_file: .env